apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx512m -Xms512m
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        name: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
        volumeMounts:
        - mountPath: elasticsearch/config/elasticsearch.yml
          name: elasticsearch-claim0
        - mountPath: elasticsearch/data
          name: elasticsearch-claim1
      restartPolicy: Always
      volumes:
      - name: elasticsearch-claim0
        persistentVolumeClaim:
          claimName: elasticsearch-claim0
      - name: elasticsearch-claim1
        persistentVolumeClaim:
          claimName: elasticsearch-claim1
status: {}
