apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-configmap
  #namespace: logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

    ## Disable X-Pack
    ## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
    ## xpack.monitoring.enabled: false
  logstash.conf: |
    input {
      udp {
        port => 5000
        codec => 'json'
      }
      tcp {
        port => 5000
        codec => 'json'
      }
    }

    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
      }
    }
